steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "southamerica-east1-docker.pkg.dev/tienda-microservicios-pabloh/image-registry/products-ms:latest",
        "-f",
        "dockerfile.prod",
        "--platform=linux/amd64",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "southamerica-east1-docker.pkg.dev/tienda-microservicios-pabloh/image-registry/products-ms:latest",
      ]
options:
  logging: CLOUD_LOGGING_ONLY